blog/urls.py
from django.urls import path
from .views import Posts ,Post_detail , PostByCategory, PostByTags
app_name='blog'
urlpatterns = [
    path('',Posts.as_view(),name='post_list'),
    path('<slug:slug>',Post_detail.as_view(),name='post_detail'),
    path('category/<str:slug>',PostByCategory.as_view(),name='post_by_category'),
    path('tag/<slug:slug>',PostByTags.as_view(),name='post_by_tag')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/',include('property.urls', namespace='property')),
    path('blog/',include('blog.urls',namespace='blog'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from .views import PropertyList,PropertyDetail
app_name='property'
urlpatterns=[
    path('',PropertyList.as_view(),name='property_list'),
    path('<slug:slug>',PropertyDetail.as_view(),name='property_detial')
]

about/models.py
from django.db import models
from django.db.models.fields.files import ImageField

# Create your models here.
class About(models.Model):
    image=models.ImageField(upload_to='about/')
    what_we_do = models.TextField(max_length=1000)
    our_mission = models.TextField(max_length=1000)
    our_goals = models.TextField(max_length=1000)
    def __str__(self):
        return str(self.id)

class Faq(models.Model):
    title = models.CharField(max_length=200)
    discription=models.TextField(max_length=1000)

    def __str__(self):
        return self.title

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls.base import reverse
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    image=models.ImageField(upload_to = 'post/')
    discription = models.TextField(max_length=50000)
    user = models.ForeignKey(User, related_name ="autho", on_delete = models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now,)
    tags = TaggableManager()
    category = models.ForeignKey("Category", related_name="post_category", on_delete=models.CASCADE)
    slug=models.SlugField(null=True,blank=True)
    
    def save(self, *args, **kwargs):
       if not self.slug:
           self.slug= slugify(self.title)
       super(Post, self).save(*args, **kwargs) # Call the real save() method

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})


    def __str__(self):
        return self.title





class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

property/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import CharField, DateTimeField, IntegerField
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.
class Property(models.Model):
    name = models.CharField(max_length=50)
    discription = models.TextField(max_length=100000)
    image = models.ImageField(upload_to='properity')
    price = models.IntegerField(default=0)
    place = models.ForeignKey("Place",related_name="property_place",on_delete=models.CASCADE)
    category = models.ForeignKey("Category",related_name="property_category",on_delete=models.CASCADE)
    slug=models.SlugField(null=True ,blank=True)

    def save(self, *args, **kwargs):
       if not self.slug:
           self.slug= slugify(f'{self.name}')
       super(Property, self).save(*args, **kwargs) # Call the real save() method

    def get_absolute_url(self):
        return reverse("property:property_detial", kwargs={"slug": self.slug})
    
    def __str__(self):
        return self.name
    

class Images(models.Model):
    property = models.ForeignKey(Property,related_name="property_images",on_delete=models.CASCADE)
    image = models.ImageField(upload_to='propertyimages')
    def __str__(self):
        return str(self.property)

class Place(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='places/')
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class PropertyReview(models.Model):
    user = models.ForeignKey(User,related_name="author",on_delete=models.CASCADE)
    property = models.ForeignKey(Property,related_name="property_review",on_delete=models.CASCADE)
    rate = models.IntegerField(default=0)
    feedback = models.TextField(max_length=2000)
    def __str__(self):
        return str(self.property)
count=(
    (1,1),
(2,2),
(3,3),
(4,4),
(5,5))
class PropertyBook(models.Model):
    user = models.ForeignKey(User,related_name="book_owner",on_delete=models.CASCADE)
    property = models.ForeignKey(Property,related_name="property_book",on_delete=models.CASCADE)
    date_from = models.DateTimeField(default=timezone.now)
    date_to = models.DateTimeField(default=timezone.now)
    guest=models.TextField(choices=count)
    childern=models.TextField(choices=count)
    def __str__(self):
        return str(self.property)
        

settings/models.py
from django.db import models

# Create your models here.
class Settings(models.Model):
    site_name = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='settings/')
    addrees = models.TextField(max_length=1000)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=254)
    description = models.TextField(max_length=1000)
    facebook = models.URLField(max_length=300)
    twitter = models.URLField(max_length=300)
    instgram = models.URLField(max_length=300)

    def __str__(self):
        return self.site_name
    

about/views.py
from django.shortcuts import render

# Create your views here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from re import template
from django.db.models.query_utils import Q
from .models import Category, Post 
from django.shortcuts import render
from django.views.generic import ListView ,DetailView
from django.db.models import Count
from taggit.models import Tag
# Create your views here.
class Posts(ListView):
    model=Post
    paginate_by=2

    def get_queryset(self):
        name=self.request.GET.get('q','')
        
        object_list=Post.objects.filter(
            
            Q(title__icontains=name) |
            Q(discription__icontains=name)
            )
        return object_list
    
    


class Post_detail(DetailView):
    model=Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recent"] = Post.objects.all()[:3]
        context['category'] = Category.objects.all().annotate(post_count = Count('post_category'))
        context['tags'] = Tag.objects.all()

        return context

class PostByCategory(ListView):
    model=Post
    # template_name='blog/post_list.html'
    def get_queryset(self):
        slug=self.kwargs['slug']
        object_list = Post.objects.filter(
            Q(category__name__icontains = slug )
        )
        return object_list


class PostByTags(ListView):
    model=Post
    def get_queryset(self):
        slug=self.kwargs['slug']
        object_list = Post.objects.filter(
            Q(tags__name__icontains = slug )
        )
        return object_list
    


    

property/views.py
from django.shortcuts import render
from django.views.generic import ListView , DetailView
from .models import Property
from django.views.generic.edit import FormMixin
from . form import PropertyBookForm
# Create your views here.
class PropertyList(ListView):
    model=Property
    paginate_by = 1

class PropertyDetail(FormMixin, DetailView):
    model=Property
    form_class=PropertyBookForm



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related"] = Property.objects.filter(category=self.get_object().category)[:2]
        return context





    def post(self,request,*args,**kwargs):
        form=self.get_form
        if form.is_valid :
            myform = form.save(commit=False)
            myform.property=self.get_object()
            myform.user = request.user
            myform.save()

settings/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
        <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
          <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a href="blog.html">Blog</a></span> <span>Blog Single</span></p>
          <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp; Articles</h1>
        </div>
      </div>
    </div>
  </div>


  <section class="ftco-section ftco-degree-bg">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ftco-animate">
          <h2 class="mb-3">{{object.title}}</h2>
          <p>
            <img src="{{object.image.url}}" alt="" class="img-fluid">
          </p>
          
          
          
        <p>{{object.discription}}</p>
          <div class="tag-widget post-tag-container mb-5 mt-5">
            <div class="tagcloud">
              {% for tag in object.tags.all %}
                <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
              {% endfor %}
              
              
            </div>
          </div>
          
          <div class="about-author d-flex p-5 bg-light">
            <div class="bio align-self-md-center mr-5">
              <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="img-fluid mb-4">
            </div>
            <div class="desc align-self-md-center">
              <h3>{{object.user}}</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>


          <div class="pt-5 mt-5">
            <h3 class="mb-5">Comments</h3>
              <div id="disqus_thread"></div>
            
          </div>

        </div> <!-- .col-md-8 -->
        <div class="col-md-4 sidebar ftco-animate">
          <div class="sidebar-box">
            <form action="{% url 'blog:post_list' %}" method='GET' class="search-form">
              <div class="form-group">
                <span class="icon fa fa-search"></span>
                <input type="text" class="form-control" name='q' placeholder="Type a keyword and hit enter">
              </div>
            </form>
          </div>
          <div class="sidebar-box ftco-animate">
            <div class="categories">
              <h3>Categories</h3>
              {% for cat in category %}
                <li><a href="{% url 'blog:post_by_category' cat %}">{{cat}} <span>({{cat.post_count}})</span></a></li>
              {% endfor %}
              
              
            </div>
          </div>

          <div class="sidebar-box ftco-animate">
            <h3>Recent Blog</h3>
            {% for post in recent %}
                <div class="block-21 mb-4 d-flex">
                    <a class="blog-img mr-4" style="background-image: url({{post.image.url}});"></a>
                    <div class="text">
                    <h3 class="heading"><a href="#">{{post.title}}</a></h3>
                    <div class="meta">
                        <div><a href="#"><span class="icon-calendar"></span> {{post.created_at}}</a></div>
                        <div><a href="#"><span class="icon-person"></span> {{post.user}}</a></div>
                        <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                    </div>
                    </div>
                </div>
            {% endfor %}
            
            
          </div>

          <div class="sidebar-box ftco-animate">
            <h3>Tag Cloud</h3>
            <div class="tagcloud">
              {% for tag in tags %}
                <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
              {% endfor %}
              
              
            </div>
          </div>

          <div class="sidebar-box ftco-animate">
            <h3>Paragraph</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
          </div>
        </div>

      </div>
    </div>
  </section> <!-- .section -->
  <script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
  
    var disqus_config = function () {
    this.page.url = "https://127.0.0.1:8000/{{Post.get_absolute_url}}";  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = "{{Post.slug}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://dj-hotel.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
        <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
          <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="index.html">Home</a></span> <span>Blog</span></p>
          <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp; Articles</h1>
        </div>
      </div>
    </div>
  </div>


  <section class="ftco-section bg-light">
    <div class="container">
      <div class="row d-flex">
        {% for new in object_list %}
            <div class="col-md-3 d-flex ftco-animate">
                <div class="blog-entry align-self-stretch">
                <a href="{{new.get_absolute_url}}" class="block-20" style="background-image: url('{{new.image.url}}');">
                </a>
                
                <div class="text p-4">
                    <span class="tag">Tips, Travel</span>
                    <h3 class="heading mt-3"><a href="{{new.get_absolute_url}}">{{new.title}}</a></h3>
                    <div class="meta mb-3">
                    <div><a href="{{new.get_absolute_url}}">{{new.created_at|date:'F j Y'}}</a></div>
                    <div><a href="{{new.get_absolute_url}}">{{new.user}}</a></div>
                    <div><a href="{{new.get_absolute_url}}" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                    </div>
                </div>
                </div>
            </div>
  
        {% endfor %}
        
      </div>
      
      {% if is_paginated %}
        <div class="row mt-5">
            <div class="col text-center">
            <div class="block-27">
                <ul>
                
                {% if page_obj.has_previous %}
                    <li><a href="?page={{page_obj.previous_page_number}}">&lt;</a></li>
                {% endif %}
                    
                {% for i in paginator.page_range %}
                    
                    {% if page_obj.number == i %}
                        <li class="active"><span>{{i}}</span></li>
                    {% else %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                    {% endif %}
                        
                {% endfor %}
                
                
                

                
                {% if page_obj.has_next %}
                    <li><a href="?page={{page_obj.next_page_number}}">&gt;</a></li>
                {% endif %}
                    
                
                </ul>
            </div>
            </div>
        </div>
      {% endif %}
          
      
    </div>
  </section>
{% endblock body %}

property/templates/property/property_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
			data-scrollax-parent="true">
			<div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
				<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
						class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a
							href="hotel.html">Hotel</a></span> <span>Hotel Single</span></p>
				<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels Details
				</h1>
			</div>
		</div>
	</div>
</div>


<section class="ftco-section ftco-degree-bg">
	<div class="container">
		
		<div class="row">
			
			<div class="col-lg-10 mx-auto">
				<div class="row">
					<div class="col-md-12 ftco-animate">
						<div class="single-slider owl-carousel">
							
							{% for p in object.property_images.all %}
								<div class="item">
									<div class="hotel-img" style="background-image: url({{p.image.url}});"></div>
								</div>
							{% endfor %}
								
							<div class="item">
								<div class="hotel-img" style="background-image: url(images/hotel-2.jpg);"></div>
							</div>
							
						</div>
					</div>
					
					<div class="col-md-12 hotel-single mt-4 mb-5 ftco-animate">
							<span>Our Best hotels &amp; Rooms</span>
							<h2>{{object.name}}</h2>
							<p class="rate mb-5">
								<span class="loc"><a href="#"><i class="icon-map"></i> 291 South 21th Street, Suite 721 New
										York NY 10016</a></span>
								<span class="star">
									<i class="icon-star"></i>
									<i class="icon-star"></i>
									<i class="icon-star"></i>
									<i class="icon-star"></i>
									<i class="icon-star-o"></i>
									8 Rating</span>
							</p>
							<p>{{object.discription}}</p>
							
					</div>
					
					<div class="col-md-12 hotel-single ftco-animate mb-5 mt-4">
						<h4 class="mb-4">Take A Tour</h4>
						<div class="block-16">
							<figure>
								<img src="images/hotel-6.jpg" alt="Image placeholder" class="img-fluid">
								<a href="https://vimeo.com/45830194" class="play-button popup-vimeo"><span
										class="icon-play"></span></a>
							</figure>
						</div>
					</div>
					<div class="col-md-12 hotel-single ftco-animate mb-5 mt-4">
						<h4 class="mb-4">Our Rooms</h4>
						<div class="row">
							<div class="col-md-4">
								<div class="destination">
									<a href="hotel-single.html" class="img img-2"
										style="background-image: url(images/room-4.jpg);"></a>
									<div class="text p-3">
										<div class="d-flex">
											<div class="one">
												<h3><a href="hotel-single.html">Hotel, Italy</a></h3>
												<p class="rate">
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star-o"></i>
													<span>8 Rating</span>
												</p>
											</div>
											<div class="two">
												<span class="price per-price">$40<br><small>/night</small></span>
											</div>
										</div>
										<p>Far far away, behind the word mountains, far from the countries</p>
										<hr>
										<p class="bottom-area d-flex">
											<span><i class="icon-map-o"></i> Miami, Fl</span>
											<span class="ml-auto"><a href="#">Book Now</a></span>
										</p>
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="destination">
									<a href="hotel-single.html" class="img img-2"
										style="background-image: url(images/room-5.jpg);"></a>
									<div class="text p-3">
										<div class="d-flex">
											<div class="one">
												<h3><a href="hotel-single.html">Hotel, Italy</a></h3>
												<p class="rate">
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star-o"></i>
													<span>8 Rating</span>
												</p>
											</div>
											<div class="two">
												<span class="price per-price">$40<br><small>/night</small></span>
											</div>
										</div>
										<p>Far far away, behind the word mountains, far from the countries</p>
										<hr>
										<p class="bottom-area d-flex">
											<span><i class="icon-map-o"></i> Miami, Fl</span>
											<span class="ml-auto"><a href="#">Book Now</a></span>
										</p>
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="destination">
									<a href="hotel-single.html" class="img img-2"
										style="background-image: url(images/room-6.jpg);"></a>
									<div class="text p-3">
										<div class="d-flex">
											<div class="one">
												<h3><a href="hotel-single.html">Hotel, Italy</a></h3>
												<p class="rate">
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star-o"></i>
													<span>8 Rating</span>
												</p>
											</div>
											<div class="two">
												<span class="price per-price">$40<br><small>/night</small></span>
											</div>
										</div>
										<p>Far far away, behind the word mountains, far from the countries</p>
										<hr>
										<p class="bottom-area d-flex">
											<span><i class="icon-map-o"></i> Miami, Fl</span>
											<span class="ml-auto"><a href="#">Book Now</a></span>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12 hotel-single ftco-animate mb-5 mt-4">
						<h4 class="mb-5">Check Availability &amp; Booking</h4>
						<form method="post" class="form">
							{% csrf_token %}
							{% bootstrap_form form %}
							{% buttons %}
								<button type="submit" class="btn btn-primary">Submit</button>
							{% endbuttons %}
						</form>
					</div>
					<div class="col-md-12 hotel-single ftco-animate mb-5 mt-4">
						<h4 class="mb-4">Review &amp; Ratings</h4>
						<div class="row">
							<div class="col-md-6">
								<form method="post" class="star-rating">
									<div class="form-check">
										<input type="checkbox" class="form-check-input" id="exampleCheck1">
										<label class="form-check-label" for="exampleCheck1">
											<p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
														class="icon-star"></i><i class="icon-star"></i><i
														class="icon-star"></i> 100 Ratings</span></p>
										</label>
									</div>
									<div class="form-check">
										<input type="checkbox" class="form-check-input" id="exampleCheck1">
										<label class="form-check-label" for="exampleCheck1">
											<p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
														class="icon-star"></i><i class="icon-star"></i><i
														class="icon-star-o"></i> 30 Ratings</span></p>
										</label>
									</div>
									<div class="form-check">
										<input type="checkbox" class="form-check-input" id="exampleCheck1">
										<label class="form-check-label" for="exampleCheck1">
											<p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
														class="icon-star"></i><i class="icon-star-o"></i><i
														class="icon-star-o"></i> 5 Ratings</span></p>
										</label>
									</div>
									<div class="form-check">
										<input type="checkbox" class="form-check-input" id="exampleCheck1">
										<label class="form-check-label" for="exampleCheck1">
											<p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
														class="icon-star-o"></i><i class="icon-star-o"></i><i
														class="icon-star-o"></i> 0 Ratings</span></p>
										</label>
									</div>
									<div class="form-check">
										<input type="checkbox" class="form-check-input" id="exampleCheck1">
										<label class="form-check-label" for="exampleCheck1">
											<p class="rate"><span><i class="icon-star"></i><i class="icon-star-o"></i><i
														class="icon-star-o"></i><i class="icon-star-o"></i><i
														class="icon-star-o"></i> 0 Ratings</span></p>
										</label>
									</div>
								</form>
							</div>
						</div>
					</div>
					<div class="col-md-12 hotel-single ftco-animate mb-5 mt-5">
						<h4 class="mb-4">Related Hotels</h4>
						<div class="row">
							{% for property in related %}
							  
							
								<div class="col-md-4">
									<div class="destination">
										<a href="hotel-single.html" class="img img-2"
											style="background-image: url(images/hotel-1.jpg);"></a>
										<div class="text p-3">
											<div class="d-flex">
												<div class="one">
													<h3><a href="hotel-single.html">Hotel, Italy</a></h3>
													<p class="rate">
														<i class="icon-star"></i>
														<i class="icon-star"></i>
														<i class="icon-star"></i>
														<i class="icon-star"></i>
														<i class="icon-star-o"></i>
														<span>8 Rating</span>
													</p>
												</div>
												<div class="two">
													<span class="price per-price">$40<br><small>/night</small></span>
												</div>
											</div>
											<p>Far far away, behind the word mountains, far from the countries</p>
											<hr>
											<p class="bottom-area d-flex">
												<span><i class="icon-map-o"></i> Miami, Fl</span>
												<span class="ml-auto"><a href="#">Book Now</a></span>
											</p>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>
					</div>

				</div>
			</div> <!-- .col-md-8 -->
		</div>
	</div>
</section> <!-- .section -->

{% endblock body %}